name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'protos/*'
      - '.github/workflows/continuous-delivery.yml'

jobs:
  PublishProtos:
    name: Publish Protos image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # renovate: tag=v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Protofiles Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2.7.0
        with:
          context: ./protos
          push: true
          tags: ghcr.io/skyra-project/grpc-protofiles:latest
