name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'protos/*'
      - '.github/workflows/continuous-delivery.yml'

jobs:
  PublishProtos:
    name: Publish Protos image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Protofiles Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./protos
          push: true
          tags: ghcr.io/skyra-project/grpc-protofiles:latest
