name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - 'protos/*'
      - '.github/workflows/continuous-delivery.yml'

jobs:
  PublishProtos:
    name: Publish Protos image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1.7.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Protofiles Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3.2.0
        with:
          context: ./protos
          push: true
          tags: ghcr.io/skyra-project/grpc-protofiles:latest
